In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from actuals_inp_handling import ActualsHandler

Testing with data gap

In [3]:
file1 = "./ErrorTestingFiles/data_gap_a.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
A few outliers were detected which were dealt with.
Saved into the database.

Testing with duplicates

In [4]:
file1 = "./ErrorTestingFiles/duplicates_a.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
Duplicates were detected in the given file.
Duplicates were detected in the given file.
A few outliers were detected which were dealt with.
Saved into the database.

Testing with invalid data types

In [5]:
file1 = "./ErrorTestingFiles/invaliddatatype.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
Error converting 'datetime' to datetime64[ns]

Testing with no column names

In [6]:
file1 = "./ErrorTestingFiles/nocolumnnames.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
Please provide a file with the correct column names.

Testing with wrong column names

In [7]:
file1 = "./ErrorTestingFiles/wrongcolnames.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
Please provide a file with the correct column names.

Testing with missing values

In [8]:
file1 = "./ErrorTestingFiles/missingcells.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
File contains missing values. A few outliers were detected which were dealt with.
Saved into the database.

Testing with incomplete data

In [9]:
file1 = "./ErrorTestingFiles/missingvalues.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
A few outliers were detected which were dealt with.
Saved into the database.

Testing with outliers

In [10]:
file1 = "./ErrorTestingFiles/outliers.csv"

handler = ActualsHandler()
handler.handle_upload_actuals([file1])

File(s) Received.
A few outliers were detected which were dealt with.
Saved into the database.

In [11]:
from forecast_inp_handling import ForecastsHandler

Testing with data gap

In [20]:
file1 = "./ErrorTestingFiles/data_gap_p.csv"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

KeyboardInterrupt:

Testing with duplicates

In [21]:
file1 = "./ErrorTestingFiles/duplicates_p.xlsx"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

File(s) Received.
File submitted contains some missing rows, which have been appropriately dealt with.Missing values were detected in the file which were dealt with.Duplicates were detected in the given file.

WARNING: You have not submitted actual values for previous days before 2021-01-21 08:00:00.
Solution implemented is to make predictions for the missing days and use them as the actual values.
As a result, the prediction accuracy may be negatively impacted.
A few outliers were detected which were dealt with.
Making predictions

,datetime,pressure,cloud_cover,temperature,wind_direction,wind_speed,date,month,type_of_day,hour
0,2021-01-15 08:00:00,1013.0,0.0,13.721890,263.0,11.0,2021-01-15,1,5,8
1,2021-01-15 09:00:00,1013.0,0.0,13.721890,263.0,11.0,2021-01-15,1,5,9
2,2021-01-15 10:00:00,1013.0,0.0,13.721890,263.0,11.0,2021-01-15,1,5,10
3,2021-01-15 11:00:00,1013.0,0.0,13.721890,263.0,11.0,2021-01-15,1,5,11
4,2021-01-15 12:00:00,1013.0,0.0,13.721890,263.0,11.0,2021-01-15,1,5,12
...,...,...,...,...,...,...,...,...,...,...
187,2021-01-23 03:00:00,1014.0,2.0,13.721886,207.0,11.0,2021-01-23,1,6,3
188,2021-01-23 04:00:00,1014.0,2.0,13.721886,207.0,11.0,2021-01-23,1,6,4
189,2021-01-23 05:00:00,1014.0,2.0,13.721886,207.0,11.0,2021-01-23,1,6,5
190,2021-01-23 06:00:00,1014.0,2.0,13.721886,207.0,11.0,2021-01-23,1,6,6
191,2021-01-23 07:00:00,1014.0,2.0,13.721886,207.0,11.0,2021-01-23,1,6,7

Testing with invalid data types

In [14]:
file1 = "./ErrorTestingFiles/invaliddatatype.csv"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

File(s) Received.
Error converting 'datetime' to datetime64[ns]

Testing with no column names

In [15]:
file1 = "./ErrorTestingFiles/nocolumnnames.csv"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

File(s) Received.
Please provide a file with the correct column names

Testing with wrong column names

In [16]:
file1 = "./ErrorTestingFiles/wrongcolnames.csv"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

File(s) Received.
Please provide a file with the correct column names

Testing with missing values

In [17]:
file1 = "./ErrorTestingFiles/missingcells_p.csv"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

File(s) Received.
Missing values were detected in the file which were dealt with.
WARNING: You have not submitted actual values for previous days before 2021-01-17 08:00:00.
Solution implemented is to make predictions for the missing days and use them as the actual values.
As a result, the prediction accuracy may be negatively impacted.
A few outliers were detected which were dealt with.
Making predictions

,datetime,pressure,cloud_cover,temperature,wind_direction,wind_speed,date,month,type_of_day,hour
0,2021-01-15 08:00:00,1013.0,0.0,11.721890,270.0,13.0,2021-01-15,1,5,8
1,2021-01-15 09:00:00,1013.0,0.0,11.721890,270.0,13.0,2021-01-15,1,5,9
2,2021-01-15 10:00:00,1013.0,0.0,11.721890,270.0,13.0,2021-01-15,1,5,10
3,2021-01-15 11:00:00,1013.0,0.0,11.721890,270.0,13.0,2021-01-15,1,5,11
4,2021-01-15 12:00:00,1013.0,0.0,11.721890,270.0,13.0,2021-01-15,1,5,12
...,...,...,...,...,...,...,...,...,...,...
91,2021-01-19 03:00:00,1013.0,5.0,13.721886,39.0,7.0,2021-01-19,1,2,3
92,2021-01-19 04:00:00,1013.0,6.0,13.721886,40.0,7.0,2021-01-19,1,2,4
93,2021-01-19 05:00:00,1013.0,6.0,13.721886,41.0,8.0,2021-01-19,1,2,5
94,2021-01-19 06:00:00,1014.0,6.0,11.721886,43.0,9.0,2021-01-19,1,2,6
95,2021-01-19 07:00:00,1014.0,7.0,13.721886,48.0,8.0,2021-01-19,1,2,7

Testing with incomplete data

In [18]:
file1 = "./ErrorTestingFiles/missingvalues_p.csv"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

Please provide 2 days' worth of data (48 hours).

Testing with outliers

In [19]:
file1 = "./ErrorTestingFiles/outliers_p.xlsx"

handler = ForecastsHandler()
handler.handle_predict_demand([file1])

File(s) Received.
A few outliers were detected which were dealt with.
Making predictions

,pressure,cloud_cover,temperature,wind_direction,wind_speed,datetime,date,month,type_of_day,hour
0,1014.5250,0.000,4.391886,61.625,3.34375,2021-01-15 08:00:00,2021-01-15,1,5,8
1,1014.9625,5.875,8.371886,73.750,7.34250,2021-01-15 09:00:00,2021-01-15,1,5,9
2,1015.1000,3.625,15.274386,111.250,5.75375,2021-01-15 10:00:00,2021-01-15,1,5,10
3,1014.8250,0.000,19.241886,34.375,9.34250,2021-01-15 11:00:00,2021-01-15,1,5,11
4,1013.9875,0.125,23.509386,59.750,9.83750,2021-01-15 12:00:00,2021-01-15,1,5,12
5,1012.8500,0.000,22.506886,274.375,10.46000,2021-01-15 13:00:00,2021-01-15,1,5,13
6,1012.0375,0.000,20.624386,269.625,19.00375,2021-01-15 14:00:00,2021-01-15,1,5,14
7,1011.5125,0.875,19.866886,280.000,22.47500,2021-01-15 15:00:00,2021-01-15,1,5,15
8,1011.3125,1.500,19.679386,299.750,19.69750,2021-01-15 16:00:00,2021-01-15,1,5,16
9,1011.4250,0.125,16.481886,300.000,18.13875,2021-01-15 17:00:00,2021-01-15,1,5,17
10,1012.1750,0.000,13.941886,322.375,13.93000,2021-01-15 18:00:00,2021-01-15,1,5,18
11,1012.9125,0.000,13.409386,319.375,11.80250,2021-01-15 19:00:00,2021-01-15,1,5,19
12,1013.7875,0.000,11.801886,347.875,13.48625,2021-01-15 20:00:00,2021-01-15,1,5,20
13,1014.3125,0.000,11.494386,73.625,9.96000,2021-01-15 21:00:00,2021-01-15,1,5,21
14,1014.7125,0.000,11.424386,22.125,6.43625,2021-01-15 22:00:00,2021-01-15,1,5,22
15,1014.4000,2.750,9.156886,180.125,7.78750,2021-01-15 23:00:00,2021-01-15,1,5,23
16,1013.8500,10.250,7.556886,46.125,3.80500,2021-01-16 00:00:00,2021-01-16,1,6,0
17,1013.5000,10.500,7.421886,39.500,3.09125,2021-01-16 01:00:00,2021-01-16,1,6,1
18,1013.1125,8.875,7.189386,43.750,2.90750,2021-01-16 02:00:00,2021-01-16,1,6,2
19,1012.8125,12.000,6.699386,39.500,3.30750,2021-01-16 03:00:00,2021-01-16,1,6,3
20,1012.7750,15.750,6.346886,73.125,7.43875,2021-01-16 04:00:00,2021-01-16,1,6,4
21,1013.1375,13.875,6.061886,67.375,3.47875,2021-01-16 05:00:00,2021-01-16,1,6,5
22,1013.8125,8.250,7.044386,72.625,3.01500,2021-01-16 06:00:00,2021-01-16,1,6,6
23,1014.7125,0.000,6.241886,69.875,3.50875,2021-01-16 07:00:00,2021-01-16,1,6,7
24,1016.0000,4.000,15.721886,84.000,11.00000,2021-01-16 08:00:00,2021-01-16,1,6,8
25,1016.0000,4.000,15.721886,92.000,11.00000,2021-01-16 09:00:00,2021-01-16,1,6,9
26,1016.0000,3.000,17.721886,120.000,10.00000,2021-01-16 10:00:00,2021-01-16,1,6,10
27,1015.0000,3.000,19.721886,149.000,10.00000,2021-01-16 11:00:00,2021-01-16,1,6,11
28,1015.0000,3.000,23.721886,178.000,9.00000,2021-01-16 12:00:00,2021-01-16,1,6,12
29,1014.0000,3.000,23.721886,222.000,10.00000,2021-01-16 13:00:00,2021-01-16,1,6,13
30,1014.0000,3.000,23.721886,265.000,11.00000,2021-01-16 14:00:00,2021-01-16,1,6,14
31,1013.0000,3.000,23.721886,309.000,12.00000,2021-01-16 15:00:00,2021-01-16,1,6,15
32,1013.0000,4.000,21.721886,314.000,13.00000,2021-01-16 16:00:00,2021-01-16,1,6,16
33,1013.0000,4.000,19.721886,320.000,15.00000,2021-01-16 17:00:00,2021-01-16,1,6,17
34,1013.0000,4.000,19.721886,325.000,17.00000,2021-01-16 18:00:00,2021-01-16,1,6,18
35,1013.0000,5.000,17.721886,293.000,15.00000,2021-01-16 19:00:00,2021-01-16,1,6,19
36,1013.0000,6.000,17.721886,262.000,14.00000,2021-01-16 20:00:00,2021-01-16,1,6,20
37,1014.0000,7.000,15.721886,230.000,13.00000,2021-01-16 21:00:00,2021-01-16,1,6,21
38,1014.0000,5.000,13.721886,161.000,11.00000,2021-01-16 22:00:00,2021-01-16,1,6,22
39,1014.0000,4.000,13.721886,91.000,10.00000,2021-01-16 23:00:00,2021-01-16,1,6,23
40,1014.0000,3.000,11.721886,22.000,9.00000,2021-01-17 00:00:00,2021-01-17,1,7,0
41,1014.0000,4.000,11.721886,28.000,8.00000,2021-01-17 01:00:00,2021-01-17,1,7,1
42,1013.0000,5.000,13.721886,33.000,8.00000,2021-01-17 02:00:00,2021-01-17,1,7,2
43,1013.0000,5.000,13.721886,39.000,7.00000,2021-01-17 03:00:00,2021-01-17,1,7,3
44,1013.0000,6.000,13.721886,40.000,7.00000,2021-01-17 04:00:00,2021-01-17,1,7,4
45,1013.0000,6.000,13.721886,41.000,8.00000,2021-01-17 05:00:00,2021-01-17,1,7,5
46,1014.0000,6.000,11.721886,43.000,9.00000,2021-01-17 06:00:00,2021-01-17,1,7,6
47,1014.0000,7.000,13.721886,48.000,8.00000,2021-01-17 07:00:00,2021-01-17,1,7,7